#!python3
# This script reads csv files exported from the UNICORN control software
# used by GE/Cytiva Akta FPLCs, and plots the data for further analysis.
import pandas as pd 
from pathlib import Path
import plotly.io as pio
import argparse as ap

class dtrace:
	'''
	The dtrace holds one data trace. Several dtrace objects can be created to
	hold all the data in a csv import.

	Arguments
	---------
	rawdata: pd.DataFrame
		The dataframe representation of the unmodified csv.
	firstcol: int
		The first column (indexes) of the trace. The ``firstcol+1`` column will
		be used as the values.
	'''

	def __init__(self,rawdata:pd.DataFrame, firstcol:int):
		self.name	  = rawdata.iloc[0,firstcol]
		self.idx_unit = rawdata.iloc[1,firstcol]
		self.val_unit = rawdata.iloc[1,firstcol+1]
		data		  = rawdata.iloc[2:,firstcol:firstcol+2].dropna()
		data.columns  = ['idx','val']
		for col in data.columns:
			if self.name !='Fraction':
				data[col] = pd.to_numeric(data[col], errors='coerce')
		self.data = data

	def __repr__(self):
		return f"\n----- Trace Object ------\nName: {self.name}\nIndex unit: {self.idx_unit}\nValue unit: {self.val_unit}\n--- Data\n{self.data.dtypes}\n{self.data}"

def printHelp():
	print("How to use this program:")
	print("- Export data from UNICORN to a csv file")
	print("- `python3 fplcPlot.py <path/to/file>.csv` to generate a plot")
	print("- This will open the interactive plot generated by plotly in your default browser.")

def main():
	# parse arguments
	ps = ap.ArgumentParser(prog="fplcPlot",description="A python script to parse csv \
			files generated by the UNICORN control software for Akta FPLCs and plot it.")
	ps.add_argument('filepath',nargs="?",help="Path to UNICORN csv export.")
	args = ps.parse_args()
	
	# check filepath validity
	fpath = Path(args.filepath)
	if not fpath.suffix.lower() == '.csv':
		raise AssertionError("File path supplied is not a csv file.")
	
	# load the data
	data = pd.read_csv(fpath,sep='\t',encoding='UTF-16',low_memory=False)
	tracen = list(data.loc[0].dropna())
	dclean = data.loc[2:]#.to_numpy()
	assert(len(data.columns)%2==0)
	split = []
	for n in range(len(data.columns)//2):
		split.append(dtrace(data,2*n))
	ls = len(split)
	#os = 0.05
	
	# Build the PyPlot plot using pio.
	layout = {'title': f'Plot of FPLC data, {fpath}'}
	#layout['xaxis'] = {'title':'Total system volume (mL)','domain':[os*(ls-1),1]} # for showing axes
	layout['xaxis'] = {'title':'Total system volume (mL)','domain':[0,1]}
	layout['legend'] = {'orientation':'h','yanchor':'bottom','y':1.02}
	traces = []
	for d in range(len(split)):
		dt = split[d]
		if dt.name == 'Fraction':
			None
		else:
			traces.append({'y': dt.data.val, 'x': dt.data.idx, 'name': dt.name, 'yaxis': f'y{d+1}'})
		#	layout[f'yaxis{d+1}'] = {'title':dt.name, 'side':'left', 'range':[dt.data.val.min(),dt.data.val.max()],'overlaying':'y1','position':os*d}
			layout[f'yaxis{d+1}'] = {'side':'left', 'range':[dt.data.val.min(),dt.data.val.max()],'anchor':'free','position':0,'showticklabels':False}
			if d > 0:
				layout[f'yaxis{d+1}']['overlaying']='y1' 
	
	#pio.show({'data': traces, 'layout': layout}, renderer='browser')
	pio.write_html({'data': traces, 'layout': layout}, fpath.with_suffix('.html'),auto_open=True)

if __name__ == "__main__":
	main()
